### ISSUE TITLE
.evilwmrc_simple not used?

### ISSUE THREAD

**Issue by premek** [mati75/evilwm#1]
Looks like `/etc/xdg/.evilwmrc_simple` is not loaded and you have to copy it to `~/.evilwmrc`

**Comment by mati75** [comment]
This is only example config. In Debian policy packages can't integrated to user files.

**Comment by premek** [comment]
What I meant was that it may be nice to have global config in etc which
would be loaded and overwritten by user config from home. But I understand
the app doesn't work like this. Thanks
